### PR TITLE
Update health

### PR DESCRIPTION
**Pull request by asaxena5**
### Summary 
Health bar moves as health decreases. It moves in discrete increments. 
Close #169 

### Testing 
Works on Mac

### Review Focus 
See if you are satisfied with the level of feedback from the health bar as compared to before

### CODE REVIEW

**Comment by Jeffrey-J-Yao** [comment]
Is only part of the health bar shown at the top of the screen? It seems to not go down at all for 10 seconds or so if you do nothing and then suddenly start dropping in chunks until its gone.

**Comment by asaxena5** [comment]
> Is only part of the health bar shown at the top of the screen? It seems to not go down at all for 10 seconds or so if you do nothing and then suddenly start dropping in chunks until its gone.

That's how its supposed to work. Your health will drop rapidly if you don't do anything at all because the longer the breaches remain unresolved, the health will decrease more often. Is that what you mean? @Jeffrey-J-Yao

**Comment by Jeffrey-J-Yao** [comment]
It feels like it drops all of a sudden though. Like its not a consistently visible decrease in health across the entire time, but like a 3 second instant loss.

**Comment by asaxena5** [comment]
> It feels like it drops all of a sudden though. Like its not a consistently visible decrease in health across the entire time, but like a 3 second instant loss.

That's fair, i can adjust that and update the pr

**Comment by mt-xing** [comment]
Can you revert your auto-format of `assets.json`? It makes the PR harder to review and causes merge conflicts with other people's changes.

**Comment by Jeffrey-J-Yao** [comment]
I'm getting an access violation in Node::setPosition after like 10 seconds or so. Did the scenegraph change or was the assets json rearranged?

**Comment by asaxena5** [comment]
there are issues with the position of the health bar from the ship segment stuff so I'm going to close this for now and open another pr once higher priority stuff is done

**Pull request closed without merging**
